export interface ChatMessage {
  id: string;
  role: "user" | "model";
  text: string;
  timestamp: string;
  isAudio?: boolean;
  imageAttached?: {
    base64: string;
    mimeType: string;
  };
  isTyping?: boolean;
  reactions?: string[];
}

export interface IdeaEvaluation {
  id: string;
  idea: string;
  title: string;
  approved: boolean;
  overallScore: number;
  feasibilityScore: number;
  marketPotentialScore: number;
  innovationScore: number;
  summary: string;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
  pivotRecommendations?: string[];
  marketSizeAnalysis: string;
  timestamp: string;
}

export interface GuidanceStep {
  stepNumber: number;
  title: string;
  actionItem: string;
  technicalDetails: string;
  estimatedHours: number;
}

export interface PrototypeGuidance {
  id: string;
  ideaId: string;
  title: string;
  description: string;
  steps: GuidanceStep[];
  prototypeStack: string[];
  wireframeConcept: string;
  wireframeCode?: string;
  timestamp: string;
}

export type UIMode = "guider" | "companion" | "automatic";

export interface CustomInstructions {
  targetDomain: string;
  forbiddenTopics: string;
  personalityStyle: string;
  codePreference: string;
}

export interface ThemeSettings {
  neonGlowStrength: "soft" | "vibrant" | "extreme";
  baseContrast: "normal" | "high";
  accentColor: string;
}

export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  activeMode: UIMode;
  timestamp: string;
  titleAutoGenerated?: boolean;
  tags?: string[];
}
