export interface MarketAnalysisReport {
  id: string;
  ideaTitle: string;
  tagline: string;
  category: string;
  date: string;
  viabilityScore: number;
  riskLevel: "Low" | "Medium" | "High";
  tamEstimate: string;
  samEstimate: string;
  somEstimate: string;
  executiveSummary: string;
  targetAudience: {
    persona: string;
    painPoints: string[];
    willingnessToPay: string;
  };
  competitors: {
    name: string;
    strengths: string;
    weakness: string;
    ourEdge: string;
  }[];
  swot: {
    strengths: string[];
    weaknesses: string[];
    opportunities: string[];
    threats: string[];
  };
  unitEconomics: {
    pricingModel: string;
    estimatedCac: string;
    estimatedLtv: string;
    paybackPeriod: string;
  };
  goToMarket: {
    primaryChannels: string[];
    viralHook: string;
    milestones: { phase: string; goal: string }[];
  };
  keyRecommendations: string[];
}

export interface ChatMessage {
  id: string;
  role: "user" | "model";
  text: string;
  timestamp: string;
  isAudio?: boolean;
  imageAttached?: {
    base64: string;
    mimeType: string;
    fileName?: string;
  };
  isTyping?: boolean;
  reactions?: string[];
  isPinned?: boolean;
  marketReport?: MarketAnalysisReport;
}

export interface IdeaEvaluation {
  id: string;
  idea: string;
  title: string;
  approved: boolean;
  overallScore: number;
  feasibilityScore: number;
  marketPotentialScore: number;
  innovationScore: number;
  summary: string;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
  pivotRecommendations?: string[];
  marketSizeAnalysis: string;
  timestamp: string;
}

export interface GuidanceStep {
  stepNumber: number;
  title: string;
  actionItem: string;
  technicalDetails: string;
  estimatedHours: number;
}

export type MilestoneStatus = "todo" | "in_progress" | "completed";

export interface PrototypeMilestone {
  id: string;
  stepNumber: number;
  title: string;
  description: string;
  estimatedHours: number;
  status: MilestoneStatus;
  order: number;
  dueDate?: string;
}

export interface PrototypeGuidance {
  id: string;
  ideaId: string;
  title: string;
  description: string;
  steps: GuidanceStep[];
  prototypeStack: string[];
  wireframeConcept: string;
  wireframeCode?: string;
  timestamp: string;
}

export type UIMode = "guider" | "companion" | "automatic";

export interface CustomInstructions {
  targetDomain: string;
  forbiddenTopics: string;
  personalityStyle: string;
  codePreference: string;
}

export interface OwnerProfile {
  name: string;
  className: string;
  age: string;
  appTitle: string;
}

export interface UserProfile {
  name: string;
  occupation: string;
  age: string;
  details: string;
  avatar?: string;
  isSetupCompleted?: boolean;
}

export type AppLanguage = "en" | "hi" | "hinglish" | "es" | "fr" | "de" | "ja";

export interface LanguageOption {
  code: AppLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

export interface ThemeSettings {
  neonGlowStrength: "soft" | "vibrant" | "extreme";
  baseContrast: "normal" | "high";
  accentColor: string;
  // UI Design & Layout Customization
  chatBubbleStyle?: "glass" | "minimal" | "rounded_pill" | "retro_card" | "cyber_border";
  fontFamily?: "modern_sans" | "tech_mono" | "serif_editorial" | "space_grotesk";
  uiDensity?: "compact" | "comfortable" | "spacious";
  chatBackgroundTexture?: "clean_dark" | "cyber_grid" | "ambient_dots" | "radial_glow";
  cornerRadius?: "sharp" | "rounded" | "soft" | "pill";
  chatHeaderStyle?: "full" | "compact" | "glass_floating";
  showAvatars?: boolean;
  showTimestamps?: boolean;
  glassBlurFx?: boolean;
}

export const DEFAULT_THEME_SETTINGS: ThemeSettings = {
  neonGlowStrength: "vibrant",
  baseContrast: "normal",
  accentColor: "#00e5ff",
  chatBubbleStyle: "glass",
  fontFamily: "modern_sans",
  uiDensity: "comfortable",
  chatBackgroundTexture: "clean_dark",
  cornerRadius: "rounded",
  chatHeaderStyle: "full",
  showAvatars: true,
  showTimestamps: true,
  glassBlurFx: true,
};

export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  activeMode: UIMode;
  timestamp: string;
  titleAutoGenerated?: boolean;
  tags?: string[];
}

export interface PromptTemplate {
  id: string;
  title: string;
  content: string;
  category: string;
  tags?: string[];
  createdAt: number;
}

export const DEFAULT_PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: "tpl_decision_create",
    title: "Create New Decision",
    category: "Decision Mirror",
    content: "Decision Title: \nOptions Considered: \nExpected Outcome: \nWhy this choice: ",
    createdAt: Date.now() - 100000,
  },
  {
    id: "tpl_decision_compare",
    title: "Compare Plan vs Actual",
    category: "Decision Mirror",
    content: "Original Decision Plan: \nWhat Actually Happened: \nKey Learnings & Surprises: ",
    createdAt: Date.now() - 90000,
  },
  {
    id: "tpl_deja_vu",
    title: "Decision Déjà Vu Check",
    category: "Decision Mirror",
    content: "I am facing a decision about [topic]. Have I made a similar decision in the past? What pattern should I watch out for?",
    createdAt: Date.now() - 80000,
  },
  {
    id: "tpl_code_review",
    title: "Code Architecture & Bug Audit",
    category: "Coding",
    content: "Review the following code for logical errors, edge cases, performance bottlenecks, and cleanliness:\n\n```ts\n\n```",
    createdAt: Date.now() - 70000,
  },
  {
    id: "tpl_study_breakdown",
    title: "Study Topic & Mindmap",
    category: "Study",
    content: "Break down the topic [Topic Name] into 5 core concepts, clear practical analogies, key equations/formulas, and active recall questions.",
    createdAt: Date.now() - 60000,
  },
  {
    id: "tpl_business_model",
    title: "Startup Idea Evaluation",
    category: "Strategy",
    content: "Evaluate this product/idea: [Idea Name]. Analyze value proposition, target user persona, moat, and key execution risks.",
    createdAt: Date.now() - 50000,
  },
];

