export interface MarketAnalysisReport {
  id: string;
  ideaTitle: string;
  tagline: string;
  category: string;
  date: string;
  viabilityScore: number;
  riskLevel: "Low" | "Medium" | "High";
  tamEstimate: string;
  samEstimate: string;
  somEstimate: string;
  executiveSummary: string;
  targetAudience: {
    persona: string;
    painPoints: string[];
    willingnessToPay: string;
  };
  competitors: {
    name: string;
    strengths: string;
    weakness: string;
    ourEdge: string;
  }[];
  swot: {
    strengths: string[];
    weaknesses: string[];
    opportunities: string[];
    threats: string[];
  };
  unitEconomics: {
    pricingModel: string;
    estimatedCac: string;
    estimatedLtv: string;
    paybackPeriod: string;
  };
  goToMarket: {
    primaryChannels: string[];
    viralHook: string;
    milestones: { phase: string; goal: string }[];
  };
  keyRecommendations: string[];
}

export interface ChatMessage {
  id: string;
  role: "user" | "model";
  text: string;
  timestamp: string;
  isAudio?: boolean;
  imageAttached?: {
    base64: string;
    mimeType: string;
  };
  isTyping?: boolean;
  reactions?: string[];
  isPinned?: boolean;
  marketReport?: MarketAnalysisReport;
}

export interface IdeaEvaluation {
  id: string;
  idea: string;
  title: string;
  approved: boolean;
  overallScore: number;
  feasibilityScore: number;
  marketPotentialScore: number;
  innovationScore: number;
  summary: string;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
  pivotRecommendations?: string[];
  marketSizeAnalysis: string;
  timestamp: string;
}

export interface GuidanceStep {
  stepNumber: number;
  title: string;
  actionItem: string;
  technicalDetails: string;
  estimatedHours: number;
}

export interface PrototypeGuidance {
  id: string;
  ideaId: string;
  title: string;
  description: string;
  steps: GuidanceStep[];
  prototypeStack: string[];
  wireframeConcept: string;
  wireframeCode?: string;
  timestamp: string;
}

export type UIMode = "guider" | "companion" | "automatic";

export interface CustomInstructions {
  targetDomain: string;
  forbiddenTopics: string;
  personalityStyle: string;
  codePreference: string;
}

export interface OwnerProfile {
  name: string;
  className: string;
  age: string;
  appTitle: string;
}

export interface UserProfile {
  name: string;
  occupation: string;
  age: string;
  details: string;
  isSetupCompleted?: boolean;
}

export type AppLanguage = "en" | "hi" | "hinglish" | "es" | "fr" | "de" | "ja";

export interface LanguageOption {
  code: AppLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

export interface ThemeSettings {
  neonGlowStrength: "soft" | "vibrant" | "extreme";
  baseContrast: "normal" | "high";
  accentColor: string;
}

export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  activeMode: UIMode;
  timestamp: string;
  titleAutoGenerated?: boolean;
  tags?: string[];
}
